# Generated by Django 5.0.6 on 2024-05-16 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 16, 13, 4, 58, 277064, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
